Fix undefined reference to getSymbols when using the pythonAPI.  Thanks to dpm for smart fix. Also add new list option updates to the CLI list function (ranksandthreads and pidsandthreads) which produce lists with rank:pthreadid or pid:pthreadid for all threads in the experiment.